
export const dandiVideos = [
  {
    id: 1,
    title: "The Struggle Begins",
    duration: "15:00",
    thumbnail: "video_assets/dandi/thumbnails/ep_1.png",
    videoUrl: "video_assets/dandi/video/ep_1.mp4",
    views: 12543,
    uploadDate: "2 days ago",
  },
  {
    id: 2,
    title: "The Journey To Dandi",
    duration: "15:00",
    thumbnail: "video_assets/dandi/thumbnails/ep_2.png",
    videoUrl: "video_assets/dandi/video/ep_2.mp4",
    views: 8976,
    uploadDate: "3 days ago",
  },
  {
    id: 3,
    title: "Breaking The Salt Law",
    duration: "10:00",
    thumbnail: "video_assets/dandi/thumbnails/ep_3.png",
    videoUrl: "video_assets/dandi/video/ep_3.mp4",
    views: 15678,
    uploadDate: "5 days ago",
  },
  {
    id: 4,
    title: "The Crackdown and Global Impact",
    duration: "25:00",
    thumbnail: "video_assets/dandi/thumbnails/ep_4.png",
    videoUrl: "video_assets/dandi/video/ep_4.mp4",
    views: 9432,
    uploadDate: "1 week ago",
  },
  {
    id: 5,
    title: "Unity And Legacy",
    duration: "45:00",
    thumbnail: "video_assets/dandi/thumbnails/ep_5.png",
    videoUrl: "video_assets/dandi/video/ep_5.mp4",
    views: 20145,
    uploadDate: "1 week ago",
  },
];

export const taxation = [
  {
    id: 1,
    title: "Introduction to Taxation in India",
    duration: "16:00",
    thumbnail: "video_assets/taxation/thumbnails/ep_1.png",
    videoUrl: "video_assets/taxation/video/ep_1.mp4",
    views: 12543,
    uploadDate: "2 days ago",
  },
  {
    id: 2,
    title: "GST and How Taxes Benefit Society",
    duration: "16:00",
    thumbnail: "video_assets/taxation/thumbnails/ep_2.png",
    videoUrl: "video_assets/taxation/video/ep_2.mp4",
    views: 8976,
    uploadDate: "3 days ago",
  },
  {
    id: 3,
    title: "Why we need taxes?",
    duration: "15:00",
    thumbnail: "video_assets/taxation/thumbnails/ep_3.png",
    videoUrl: "video_assets/taxation/video/ep_3.mp4",
    views: 15678,
    uploadDate: "5 days ago",
  },
  {
    id: 4,
    title: "Differnt types of taxes",
    duration: "25:00",
    thumbnail: "video_assets/taxation/thumbnails/ep_4.png",
    videoUrl: "video_assets/taxation/video/ep_4.mp4",
    views: 9432,
    uploadDate: "1 week ago",
  },
  {
    id: 5,
    title: "Taxes makes the world a better place to live",
    duration: "15:00",
    thumbnail: "video_assets/taxation/thumbnails/ep_5.png",
    videoUrl: "video_assets/taxation/video/ep_5.mp4",
    views: 20145,
    uploadDate: "1 week ago",
  },
];

export const blackHoles = [
  {
    id: 1,
    title: "A Mysterious Spot in Space: A Black Hole",
    duration: "26:00",
    thumbnail: "video_assets/black_hole/thumbnails/ep_1.png",
    videoUrl: "video_assets/black_hole/video/ep_1.mp4",
    views: 12543,
    uploadDate: "2 days ago",
  },
  {
    id: 2,
    title: "Falling Into Forever",
    duration: "15:00",
    thumbnail: "video_assets/black_hole/thumbnails/ep_2.png",
    videoUrl: "video_assets/black_hole/video/ep_2.mp4",
    views: 8976,
    uploadDate: "3 days ago",
  },
  {
    id: 3,
    title: "Space-Time Mysteries: Can We Travel Through Time?",
    duration: "25:00",
    thumbnail: "video_assets/black_hole/thumbnails/ep_3.png",
    videoUrl: "video_assets/black_hole/video/ep_3.mp4",
    views: 15678,
    uploadDate: "5 days ago",
  },
  {
    id: 4,
    title: "A Star’s Final Secret: Black Holes!",
    duration: "31:00",
    thumbnail: "video_assets/black_hole/thumbnails/ep_4.png",
    videoUrl: "video_assets/black_hole/video/ep_4.mp4",
    views: 9432,
    uploadDate: "1 week ago",
  },
  {
    id: 5,
    title: "The Secrets of Space!",
    duration: "36:00",
    thumbnail: "video_assets/black_hole/thumbnails/ep_5.png",
    videoUrl: "video_assets/black_hole/video/ep_5.mp4",
    views: 20145,
    uploadDate: "1 week ago",
  },
];

export const waterCycle = [
  {
    id: 1,
    title: "Cycle Starts, Evaporation",
    duration: "36:00",
    thumbnail: "video_assets/water_cycle/thumbnails/ep_1.png",
    videoUrl: "video_assets/water_cycle/video/ep_1.mp4",
    views: 12543,
    uploadDate: "2 days ago",
  },
  {
    id: 2,
    title: "The Cloud Party: Condensation",
    duration: "31:00",
    thumbnail: "video_assets/water_cycle/thumbnails/ep_2.png",
    videoUrl: "video_assets/water_cycle/video/ep_2.mp4",
    views: 8976,
    uploadDate: "3 days ago",
  },
  {
    id: 3,
    title: "The Rain’s Adventure: Precipitation",
    duration: "31:00",
    thumbnail: "video_assets/water_cycle/thumbnails/ep_3.png",
    videoUrl: "video_assets/water_cycle/video/ep_3.mp4",
    views: 15678,
    uploadDate: "5 days ago",
  },
  {
    id: 4,
    title: "Water Everywhere: Use It Wisely!",
    duration: "26:00",
    thumbnail: "video_assets/water_cycle/thumbnails/ep_4.png",
    videoUrl: "video_assets/water_cycle/video/ep_4.mp4",
    views: 9432,
    uploadDate: "1 week ago",
  },
];

export const defaultVideos = [
  {
    id: 1,
    title: "Getting Started with AI",
    duration: "10:00",
    thumbnail: "video_assets/default/thumbnails/ep_1.jpeg",
    videoUrl: "default_ep_1.mp4",
    views: 7654,
    uploadDate: "1 day ago",
  },
  {
    id: 2,
    title: "AI in Daily Life",
    duration: "15:00",
    thumbnail: "video_assets/default/thumbnails/ep_2.jpeg",
    videoUrl: "default_ep_2.mp4",
    views: 8765,
    uploadDate: "2 days ago",
  },
  {
    id: 3,
    title: "Future of Technology",
    duration: "20:00",
    thumbnail: "video_assets/default/thumbnails/ep_3.jpeg",
    videoUrl: "default_ep_3.mp4",
    views: 9876,
    uploadDate: "4 days ago",
  },
  {
    id: 4,
    title: "Digital Revolution",
    duration: "25:00",
    thumbnail: "video_assets/default/thumbnails/ep_4.jpeg",
    videoUrl: "default_ep_4.mp4",
    views: 12345,
    uploadDate: "1 week ago",
  },
];

